blank_issues_enabled: false
contact_links:
  - name: Support This Project
    url: https://github.com/tallguyjenks/PyRM/discussions
    about: Help support continued development on this project
  - name: More about the maintainer
    url: https://www.bryanjenks.dev/
    about: get to know the maintainer of PyRM
