version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "live"
    open-pull-requests-limit: 10
    assignees:
      - "dependabot"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: "[DEPENDABOT] GitHub Actions"
      include: "scope"
    # Specify labels for npm pull requests
    labels: "dependencies"
    # Add reviewers
    reviewers: "tallguyjenks"
    # to pip against the `develop` branch
    target-branch: "prod"

  # Maintain dependencies for python with poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "live"
    open-pull-requests-limit: 10
    assignees:
      - "dependabot"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: "[DEPENDABOT] pip prod"
      prefix-development: "[DEPENDABOT] pip dev"
      include: "scope"
    # Specify labels for npm pull requests
    labels: "dependencies"
    # Add reviewers
    reviewers: "tallguyjenks"
    # to pip against the `develop` branch
    target-branch: "prod"
